@startuml Get Current Logged In User

footer Page %page% of %lastpage%
title "Get Current Logged In User"

participant "user/admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:auth" as controllerAuth
participant "<<model>>\n:User" as modelUser

' User sends a POST request to get current user data
user->server ++: req.post('/api/v1/auth/me')
' Controller finds the user by ID
server->controllerAuth ++: getMe()
controllerAuth -> modelUser ++: User.findById(req.user.id)
modelUser -> database ++: Query user by ID
database --> modelUser --: userFound
' Controller sends the user data in the response
controllerAuth -> user --: response with user data

@enduml
