@startuml Login User

footer Page %page% of %lastpage%
title "Login User"

participant "user/admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:auth" as controllerAuth
participant "<<model>>\n:User" as modelUser
participant "<<token response>>\n:sendTokenRespond" as sendTokenRespond

' User sends a POST request to login
user->server ++: req.post('/api/v1/auth/login')
server->controllerAuth ++: login()
' Controller checks for user by email
controllerAuth -> modelUser ++: User.findOne({ email })
modelUser -> database ++: Query user by email
database --> modelUser --: userFound
' Controller checks if password matches
controllerAuth -> modelUser ++: user.matchPassword(password)
modelUser -> modelUser --: isMatch
' If password matches, controller sends response with token
controllerAuth -> sendTokenRespond ++: create JWT token and set cookie
sendTokenRespond -> user --: response with token and cookie

@enduml
