@startuml User Logout

footer Page %page% of %lastpage%
title "User Logout"

participant "user/admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:auth" as controllerAuth
participant "<<model>>\n:Blacklist" as modelBlacklist

' User sends GET request to logout
user->server ++: req.get('/api/v1/auth/logout')
' Controller checks if token is present in cookies
server->controllerAuth ++: logout()
controllerAuth -> modelBlacklist ++: Blacklist.create(token)
' Server clears the cookie and responds with success message
server->user --: response with logout success

@enduml
