@startuml Register User

footer Page %page% of %lastpage%
title "Register User"

participant "user/admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:auth" as controllerAuth
participant "<<model>>\n:User" as modelUser

' usersends a POST request to register a new user
user->server ++: req.post('/api/v1/auth/register')
server->controllerAuth ++: register()
' Controller creates a new user in the database
controllerAuth -> modelUser ++: User.create()
modelUser -> database ++: Save user details
database --> modelUser --: userCreated
' Controller sends the response with the user data and token
controllerAuth -> user --: response with token

@enduml
