@startuml Update User

footer Page %page% of %lastpage%
title "Update User"

participant "user/admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<controllers>>\n:users" as controllerUsers
participant "<<model>>\n:User" as modelUser

' User sends PUT request to update user
user->server ++: req.put('/api/v1/users/:id')
' Server checks if user is authorized to update
server->controllerUsers ++: updateUser()
controllerUsers -> modelUser ++: User.findByIdAndUpdate()
' Server responds with the updated user data
server->user --: response with updated user

@enduml
