@startuml Get All Bookings

footer Page %page% of %lastpage%
title "Get All Bookings"

participant "admin" as user
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:bookings" as routerbooking
participant "<<controllers>>\n:bookings" as controllersbookings
participant "<<model>>\n:Booking" as modelBooking
database "<<MongoDB>>\n:DentistBooking" as DentistBookingDatabase

' user sends a GET request to fetch all bookings
user->server ++: req.get('/api/v1/bookings')
server->routerbooking ++: app.use('/api/v1/bookings', bookings)
routerbooking -> controllersbookings ++: getBookings()
' Controller fetches bookings from the database
controllersbookings -> modelBooking ++: findBookings()
modelBooking -> DentistBookingDatabase ++: Booking.find()
DentistBookingDatabase --> modelBooking --: bookings
' Controller sends response back to user
controllersbookings <-- modelBooking --: bookings
controllersbookings -> user --: response

@enduml
